/**
 * Core types for the Canton SDK.
 *
 * These are generic, template-agnostic types that model the Daml JSON Ledger
 * API's wire format. Application-specific payload types (e.g. TradeDealPayload)
 * are defined by consumers or generated by canton-codegen.
 */

/** Fully qualified Daml template identifier: `packageId:Module:Entity`. */
export type TemplateId = string;

/** Opaque contract identifier returned by the ledger on create/exercise. */
export type ContractId<_T = unknown> = string;

/** A party identifier on the Canton ledger. */
export type Party = string;

/** A contract as returned by the JSON Ledger API (create result or query row). */
export interface LedgerContract<T = Record<string, unknown>> {
  contractId: ContractId<T>;
  templateId: TemplateId;
  payload: T;
}

/** Result of exercising a choice on a contract. */
export interface ExerciseResult<T = unknown> {
  exerciseResult: T;
  events: LedgerEvent[];
}

/** A create or archive event from the ledger. */
export interface LedgerEvent {
  created?: {
    contractId: string;
    templateId: string;
    payload: Record<string, unknown>;
    signatories: string[];
    observers: string[];
  };
  archived?: {
    contractId: string;
    templateId: string;
  };
}

/** Party allocation result. */
export interface PartyDetails {
  identifier: Party;
  displayName?: string;
  isLocal?: boolean;
}

/** Contract key — either a primitive or a record with named fields. */
export type ContractKey = string | number | boolean | Record<string, unknown>;

/** Configuration for the CantonClient. */
export interface CantonConfig {
  /** Base URL of the Daml JSON Ledger API (e.g. http://localhost:7575). */
  ledgerApiUrl: string;

  /** Auth provider for generating ledger tokens. */
  auth: AuthProvider;

  /** Daml application ID (default: "canton-sdk"). */
  applicationId?: string;

  /** Daml ledger ID (default: "sandbox"). */
  ledgerId?: string;

  /** Connection retry config. */
  retry?: RetryConfig;

  /** Health check interval in ms (0 to disable, default: 30000). */
  healthCheckInterval?: number;

  /** Request timeout in ms per HTTP call (default: 30000). */
  requestTimeoutMs?: number;
}

/** Auth provider interface — pluggable strategy for obtaining ledger JWTs. */
export interface AuthProvider {
  /** Get a JWT token for the given party configuration. */
  getToken(opts: TokenRequest): Promise<string> | string;
}

/** Token request — describes what permissions the token should carry. */
export interface TokenRequest {
  actAs?: Party[];
  readAs?: Party[];
  admin?: boolean;
}

/** Retry configuration for transient failures. */
export interface RetryConfig {
  /** Max number of retry attempts (default: 3). */
  maxRetries?: number;
  /** Initial backoff delay in ms (default: 1000). */
  initialDelayMs?: number;
  /** Backoff multiplier (default: 2). */
  backoffMultiplier?: number;
  /** Maximum delay in ms (default: 30000). */
  maxDelayMs?: number;
}

/** Health status returned by the client. */
export interface HealthStatus {
  ok: boolean;
  ledgerApiUrl: string;
  checkedAt: number;
  error?: string;
}

/** Options for the query command. */
export interface QueryOptions {
  actAs?: Party;
  readAs?: Party[];
  filter?: Record<string, unknown>;
}
